<?php
/**
 * Implementation of hook_menu_alter().
 */
function redirect_from_node_menu_alter(&$items) {
  $items['node']['page callback'] = '_internal_custom_function_name_here_redirect_to_frontpage';
}

/**
 * Redirect back to the frontpage for specific pages.
 */
function _internal_custom_function_name_here_redirect_to_frontpage() {
  // Check GET parameter? if it == node or node/ then redirect
  if (preg_match('|^node/?$|', $_GET['q'])) { 
    drupal_goto('home');
    //$form_state['redirect'] = 'home';
  }
  
}


/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function redirect_from_node_wysiwyg_editor_settings_alter(&$settings, $context) {
  
  if ($context['profile']->editor == 'tinymce') {    
    $settings['gecko_spellcheck'] = true;
    $settings['forced_root_block'] = false;
    $settings['force_br_newlines'] = true;
    $settings['force_p_newlines'] = false;
   
    drupal_set_message(t("Test " ));
 
   
    // Any init setting taking a string, boolean, number or array/object holding those types can be overridden/forced here.
  }
}
?>